all: frontendgui.py cashingui.py confirmgui.py

frontendgui.py: frontend.ui
	pyuic5 frontend.ui -o frontendgui.py


cashingui.py: cashin.ui
	pyuic5 cashin.ui -o cashingui.py

confirmgui.py: confirm.ui
	pyuic5 confirm.ui -o confirmgui.py